### ISSUE TITLE
Captive Missions.

### ISSUE THREAD

**Issue by Ghostrider-DbD-** [Ghostrider-DbD-/blckeagles-revisited-RC#101]
The basic idea will be to spawn an AI unit and assign it a captive designation whereby AI will not fire on it. Criteria for mission completion would be that all AI assigned to that mission are dead and the captive is alive and a player stand within a meter of the captive thereby releasing it. It may be possible to have players interact with captives to 'release' them which would add a layer of coolness. I would need to sort out how to handle the communication between clients and server for that last part.

**Comment by Ghostrider-DbD-** [comment]
This may require some means for interacting with AI through adding something to relevant configs in exile and epoch.

**Comment by northrivergeek** [comment]
sounds good

**Comment by Ghostrider-DbD-** [comment]
Working as of Version 6.81 Build 123.
Need some interesting scenery.
