### ISSUE TITLE
Error Undefined variable in expression: blck_maxspawnedmissions

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#150]
16:40:18 Error in expression <s.sqf"
;

if (blck_missionsRunning >= blck_maxSpawnedMissions) exitWith {

};>
16:40:18   Error position: <blck_maxSpawnedMissions) exitWith {

};>
16:40:18   Error Undefined variable in expression: blck_maxspawnedmissions
16:40:18 File q\addons\custom_server\Compiles\Missions\GMS_fnc_spawnPendingMissions.sqf..., line 6

**Comment by ehylla93** [comment]
Also missions wont spawn when this error appears in RPT. But mission spawn message will show up ingame.

**Comment by ehylla93** [comment]
[a3chernarus-test_2020-05-28_18-53-08.txt](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/4697143/a3chernarus-test_2020-05-28_18-53-08.txt)

**Comment by ehylla93** [comment]
[a3virolahti_2020-05-30_20-01-18.txt](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/4706285/a3virolahti_2020-05-30_20-01-18.txt)

Also another log.

The problem mentioned is only happening on Virolahti.

**Comment by Ghostrider-DbD-** [comment]
OK Thanks - will look into it. Is that a specific map then?

**Comment by ehylla93** [comment]
Well, I have that error message on several maps. But only Virolahti has the problem, that missions not spawning sporadic but messages are announcing spawns.

I can confirm:  blck_maxspawnedmissions is not in blck_configs.sqf, but in blck_configs_mil.sqf

Readded it.

**Comment by Ghostrider-DbD-** [comment]
Is this the map in question?
https://steamcommunity.com/sharedfiles/filedetails/?id=1926513010&searchtext=Virolahti+
What Version/build are you running?

**Comment by ehylla93** [comment]
Yep, that is the map currently running. Latest version.

**Comment by Ghostrider-DbD-** [comment]
I will run a test to ensure that the map center and radius are appropriate. There should be defaults defined that are universal so at least some missions should spawn regardless of whether or not there are pre-defined settings for a map. Is the error for blck_maxspawnedmissions the only one in your logs?

**Comment by ehylla93** [comment]
blck_maxspawnedmissions has been fixed by adding it into blck_configs.sqf

Currenr error is now:

17:10:47 Error in expression <else {
_players = allPlayers select {_x distance _coords < _range};
};


private>
17:10:47   Error position: <distance _coords < _range};
};


private>
17:10:47   Error 4 elements provided, 3 expected
17:10:47 File q\addons\custom_server\Compiles\Functions\GMS_fnc_playerInRange.sqf..., line 19

**Comment by Ghostrider-DbD-** [comment]
That error was fixed in later builds of the experimental branch.
From your logs, it looks like you are using build 200.

**Comment by Ghostrider-DbD-** [comment]
Please give build 205 on the experimental branch a try.
I added map configs for vtl. Many other little errors have also been fixed. There is just one left that I am aware of having to do with AI counts and the NUM (pirate) missions.

**Comment by ehylla93** [comment]
Problem seems to be fixed.
