### ISSUE TITLE
UMS / Static spawned althought deactivated

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#151]
blck_numberUnderwaterDynamicMissions = -1;  // Values from -1 (no UMS) to N (N Underwater missions will be spawned; static UMS units and subs will be spawned.

but UMS missions spawning anyway - temporary solution to exclude these missions in GMS_UMS_StaticMissions_Lists.sqf

same for static missions - but there is no option for them, so also exclude the missions in GMS_StaticMissions_Lists.sqf

**Comment by Ghostrider-DbD-** [comment]
Thanks - will look into this as part of updates for Build 204 / Experimental

**Comment by Ghostrider-DbD-** [comment]
blck_numberUnderwaterDynamicMissions = -1; 
This setting should prevent the dynamically spawned missions from spawning but will not influence the static ones at all. Your solution to comment out the static mission is the intendended one.
