### ISSUE TITLE
AI with Dynamic Loadout don't have any ammo for main gun

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#153]
As the topic says: AI don't have any magazine for their main gun. Only pistol is usable.

blck_maximumItemPriceInAI_Loadouts = 100000;
blck_useConfigsGeneratedLoadouts = true;
blck_logBlacklistedItems = true;

also did a small change in blck_dynamicConfigs.sqf

if (toLower(blck_modType)  isEqualTo "exile") then
	{
		_price = getNumber(missionConfigFile >> "CfgExileArsenal" >> _x >> "price");
		_sellPrice = getNumber(missionConfigFile >> "CfgExileArsenal" >> _x >> "sellPrice");
		//diag_log format["Item: %1 | Price: %2 | Sellprice: %3", _x, _price, _sellPrice];
	};
	if (_sellPrice != 1 && _price < blck_maximumItemPriceInAI_Loadouts && !(["base",_x] call BIS_fnc_inString)) then

-> added _sellPrice, because I want not to spawn items which have a sell price for 1 (e. g. high loot buildings)

So far no errors in RPT log.

Also added this in @GMS\addons\custom_server\Compiles\Units\GMS_fnc_spawnUnit.sqf again:

if (typeName _ammoChoices isEqualTo "ARRAY" and !(_ammochoices isEqualTo [])) then 
{
	_unit addMagazines [selectRandom _ammoChoices, 3];
} else {
	diag_log format["<ERROR> _fnc_spawnUnit: _weap = %1 | _ammoChoices = %2 | time = %3",_weap,_ammoChoices,time];
};

No effect.

[a3chernarus_2020-07-21_20-00-57.txt](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/4955533/a3chernarus_2020-07-21_20-00-57.txt)

[a3chernarus_2020-07-21_20-28-56.txt](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/4955532/a3chernarus_2020-07-21_20-28-56.txt)

**Comment by ehylla93** [comment]
Temp fix:

in GMS_fnc_SpawnUnit.sqf add under lines

if (_weaponList isEqualTo []) then {_weaponList = call blck_fnc_selectAILoadout};
_weap = selectRandom _weaponList;  
_unit addWeaponGlobal  _weap;
_ammoChoices = getArray (configFile >> "CfgWeapons" >> _weap >> "magazines");

these line: _unit addMagazines [selectRandom _ammoChoices, 4]; (four is the amount of magazines, you can set them to your preferred value)

**Comment by Ghostrider-DbD-** [comment]
This should be fixed in build 214, Experimental Build.
