### ISSUE TITLE
Missing Worlds chernarus_winter ; cup_chernarus_a3

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#154]
Both share the same settings like Chernarus:
blck_mapCenter = [7100, 7750, 0];
blck_mapRange = 6000;

**Comment by Ghostrider-DbD-** [comment]
I will add this to the next build. 
Thank you for letting me know.

**Comment by Ghostrider-DbD-** [comment]
Addressed in build 215, Experimental Branch.
