### ISSUE TITLE
Possible HC crash using latest version

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#161]
[custom_server_old.zip](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/5233294/custom_server_old.zip)

[custom_server_new.zip](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/5233299/custom_server_new.zip)

[a3altis-hc_2020-09-15_20-01-11.zip](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/5233312/a3altis-hc_2020-09-15_20-01-11.zip)

[a3altis_2020-09-15_20-01-11.zip](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/5233321/a3altis_2020-09-15_20-01-11.zip)

**Comment by ehylla93** [comment]
Maybe it's also related to BattlEye as you can see in a3altis_2020-09-15_20-01-11.zip

Problem didnt occured after chaning to custom_server_old

**Comment by Ghostrider-DbD-** [comment]
please send the logs to deadman or dwarden at Arma3 discord.
