### ISSUE TITLE
blck_dynamicConfigs.sqf > Error in RPT

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#175]
15:22:55   Error position: <_cupw;

blck_pistols = _wpnHandGun;
blck>
15:22:55   Error Missing ;
15:22:55 File q\addons\custom_server\Configs\blck_dynamicConfigs.sqf..., line 172
15:22:55 Error in expression <achIndex,_x];};
} forEach _ffaa + _lago _cupw;

blck_pistols = _wpnHandGun;
blck>
15:22:55   Error position: <_cupw;

blck_pistols = _wpnHandGun;
blck>
15:22:55   Error Missing ;
15:22:55 File q\addons\custom_server\Configs\blck_dynamicConfigs.sqf..., line 172
15:22:55 Error in expression <achIndex,_x];};
} forEach _ffaa + _lago _cupw;

blck_pistols = _wpnHandGun;
blck>

I don't use FFAA or LAGO or CUP, just RHS and 3CB

So dynamic stuff is not generated because of that.

The rest is now running (redownloaded it and configured it).

**Comment by ehylla93** [comment]
I read the error message again:

private _absentWep = [];
{
	if !(_x in _allWep) then {diag_log format["_absentWep %1 = %2",_forEachIndex,_x];};
} forEach _ffaa + _lago _cupw; ---> there is a "+" missiong between _lago and _cupw

Will try it again and report to you

**Comment by ehylla93** [comment]
Okay, adding the missing "+" did the trick. There is still this error left:

18:29:06 Error in expression <hIndex,_x];};
} forEach _ffaa + _lago + _cupw;

blck_pistols = _wpnHandGun;
blck>
18:29:06   Error position: <_cupw;

blck_pistols = _wpnHandGun;
blck>
18:29:06   Error Undefined variable in expression: _cupw

**Comment by Ghostrider-DbD-** [comment]
OK fixing now.

**Comment by Ghostrider-DbD-** [comment]
I placed the diagnostic code I used to generate a list of DLC and sort weapons based on DLC in comments for others who wish to check that the script functions as desired.
The new version ran without errors for me. Let me know if you find issues.

**Comment by Ghostrider-DbD-** [comment]
Resolved
