### ISSUE TITLE
Several missions wont finish

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#176]
We have a found a bug on our server.

The missions wont despawn - it is still one AI left, but the crates spawned with loot.

- Ammunition Depot (Orange)
- Resupply Camp (Green)
- Factory (Green)
- Nachschublager (is it really called like that?) (Green)

blck_missionEndCondition = "allUnitsKilled";
blck_spawnCratesTiming = "atMissionEndAir";
blck_loadCratesTiming = "atMissionCompletion";

**Comment by Ghostrider-DbD-** [comment]
OK, lower priority, will take a look.

**Comment by ehylla93** [comment]
It seems that there are multiple missions with that problem. Will update this issue with them.

**Comment by Ghostrider-DbD-** [comment]
This has come up before. One of our players speculated that the cause was AI in the helos. 
Setting  blck_killPercentage = 0.80; may solve this.
The trick will be not to lull players into a false sense of security.
Does the mission marker show all AI dead under the case you mentioned above?
It may not be mission-specific if that is the behavior you are seeing.

**Comment by ehylla93** [comment]
The mission marker shows only 1 AI left.

**Comment by Ghostrider-DbD-** [comment]
That is the problem. 
With  blck_killPercentage  = 0.9999; // (default) the mission wont show as completed until all units are dead.

**Comment by ehylla93** [comment]
update

**Comment by Ghostrider-DbD-** [comment]
Updated to build 239 to remove some logging I put in to diagnose old issues.
Fixed a few minor issues with blck_config.sqf: it generated errors if the preprocessor command for APEX was not enabled.

Set blck_killPercentage = 0.90;
That should fix your issues.

**Comment by Ghostrider-DbD-** [comment]
I assume this was resolved with the above fix. Please reopen if the issue recurs.
