### ISSUE TITLE
HC crash using latest version

### ISSUE THREAD

**Issue by ehylla93** [Ghostrider-DbD-/blckeagles-revisited-RC#177]
related to: https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/issues/161

[a3altis-hc_2020-11-25_16-02-16.zip](https://github.com/Ghostrider-DbD-/blckeagles-revisited-RC/files/5598405/a3altis-hc_2020-11-25_16-02-16.zip)

The file included the HC log and also bidmp and mdmp

**Comment by Ghostrider-DbD-** [comment]
OK Thanks.  I will send the crash dump to Bohemia. I did not see any script errors.

**Comment by Ghostrider-DbD-** [comment]
Please keep an eye out for the new performance/profiling build which should be out soon, maybe tomorrow, and let me know if the problem persists.

**Comment by ehylla93** [comment]
Willdo, always using the latest one

Ghostrider [GRG] <notifications@github.com> schrieb am Mi., 25. Nov. 2020,
22:05:

**Comment by ehylla93** [comment]
Can you confirm that there is a possible fix for that crash included in the latest performance/profiling build? I don't want to do a live test.

**Comment by Ghostrider-DbD-** [comment]
I can try to run an HC on one of our servers over the weekend. I can not confirm that bohemia fixed the crash. My guess is they tried.

**Comment by Ghostrider-DbD-** [comment]
I believe this was resovled with one of the performance builds. Please reopen the issue if it recurs.
